name: rapport_codi
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # 앱 아이콘 생성 패키지
  flutter_launcher_icons: ^0.14.4

# 앱 아이콘 설정
flutter_launcher_icons:
  android: true
  ios: true

  # 기본 앱 아이콘
  image_path: "assets/images/app_icon.png"

  # Android Adaptive Icon
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

  # Android 13+ 테마 아이콘
  adaptive_icon_monochrome: "assets/images/app_icon_monochrome.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/