/// 이용자 관리 화면에서 사용하는 UI 모델입니다.
/// API 연결 전 샘플 단계에서는 화면에 필요한 값만 단순하게 보관합니다.
class MemberUi {
  final String id;
  final String name;
  final String gender;
  final DateTime birthDate;
  final String status;
  final DateTime statusDate;
  final String motherPhone;
  final bool mobileAppEnabled;
  final String address;
  final String email;
  final String school;
  final String disabilityType;
  final DateTime? firstConsultationAt;
  final String referralSource;
  final String memo;
  final String lastModifiedBy;
  final DateTime lastModifiedAt;

  const MemberUi({
    required this.id,
    required this.name,
    required this.gender,
    required this.birthDate,
    required this.status,
    required this.statusDate,
    required this.motherPhone,
    required this.mobileAppEnabled,
    required this.address,
    required this.email,
    required this.school,
    required this.disabilityType,
    required this.firstConsultationAt,
    required this.referralSource,
    required this.memo,
    required this.lastModifiedBy,
    required this.lastModifiedAt,
  });

  MemberUi copyWith({
    String? name,
    String? gender,
    DateTime? birthDate,
    String? status,
    DateTime? statusDate,
    String? motherPhone,
    bool? mobileAppEnabled,
    String? address,
    String? email,
    String? school,
    String? disabilityType,
    DateTime? firstConsultationAt,
    String? referralSource,
    String? memo,
    String? lastModifiedBy,
    DateTime? lastModifiedAt,
  }) {
    return MemberUi(
      id: id,
      name: name ?? this.name,
      gender: gender ?? this.gender,
      birthDate: birthDate ?? this.birthDate,
      status: status ?? this.status,
      statusDate: statusDate ?? this.statusDate,
      motherPhone: motherPhone ?? this.motherPhone,
      mobileAppEnabled: mobileAppEnabled ?? this.mobileAppEnabled,
      address: address ?? this.address,
      email: email ?? this.email,
      school: school ?? this.school,
      disabilityType: disabilityType ?? this.disabilityType,
      firstConsultationAt: firstConsultationAt ?? this.firstConsultationAt,
      referralSource: referralSource ?? this.referralSource,
      memo: memo ?? this.memo,
      lastModifiedBy: lastModifiedBy ?? this.lastModifiedBy,
      lastModifiedAt: lastModifiedAt ?? this.lastModifiedAt,
    );
  }
}

/// 이용자 관리 화면용 샘플 데이터입니다.
/// 실제 API 연결 시 Repository 응답으로 교체하면 됩니다.
final List<MemberUi> sampleMembers = [
  MemberUi(
    id: 'M001',
    name: '강도현',
    gender: '남',
    birthDate: DateTime(2022, 7, 20),
    status: '대기',
    statusDate: DateTime(2026, 8, 20),
    motherPhone: '010-5788-8545',
    mobileAppEnabled: true,
    address: '',
    email: '',
    school: '',
    disabilityType: '미응답',
    firstConsultationAt: DateTime(2025, 4, 23, 10, 50),
    referralSource: '',
    memo: '현대해상 / 이용동의서○ / 325녀2787',
    lastModifiedBy: '권하영 / 행정실장',
    lastModifiedAt: DateTime(2026, 2, 11, 15, 3),
  ),
  MemberUi(
    id: 'M002',
    name: '강시후',
    gender: '남',
    birthDate: DateTime(2020, 9, 29),
    status: '대기',
    statusDate: DateTime(2026, 8, 18),
    motherPhone: '010-8316-8606',
    mobileAppEnabled: false,
    address: '수원시 영통구',
    email: '',
    school: '새봄어린이집',
    disabilityType: '미응답',
    firstConsultationAt: null,
    referralSource: '지인 소개',
    memo: '',
    lastModifiedBy: '박병준 / 대표님',
    lastModifiedAt: DateTime(2026, 8, 18, 11, 20),
  ),
  MemberUi(
    id: 'M003',
    name: '강지민',
    gender: '남',
    birthDate: DateTime(2021, 8, 17),
    status: '대기',
    statusDate: DateTime(2026, 8, 17),
    motherPhone: '010-9487-1386',
    mobileAppEnabled: false,
    address: '',
    email: '',
    school: '',
    disabilityType: '언어장애',
    firstConsultationAt: null,
    referralSource: '인터넷 검색',
    memo: '',
    lastModifiedBy: '박병준 / 대표님',
    lastModifiedAt: DateTime(2026, 8, 17, 9, 40),
  ),
  MemberUi(
    id: 'M004',
    name: '공도현',
    gender: '남',
    birthDate: DateTime(2020, 8, 12),
    status: '대기',
    statusDate: DateTime(2026, 8, 14),
    motherPhone: '010-5746-8784',
    mobileAppEnabled: true,
    address: '',
    email: '',
    school: '',
    disabilityType: '미응답',
    firstConsultationAt: null,
    referralSource: '',
    memo: '',
    lastModifiedBy: '박병준 / 대표님',
    lastModifiedAt: DateTime(2026, 8, 14, 14, 5),
  ),
  MemberUi(
    id: 'M005',
    name: '공미소',
    gender: '여',
    birthDate: DateTime(2019, 1, 11),
    status: '종결',
    statusDate: DateTime(2026, 6, 30),
    motherPhone: '010-5746-8784',
    mobileAppEnabled: false,
    address: '',
    email: '',
    school: '',
    disabilityType: '미응답',
    firstConsultationAt: null,
    referralSource: '홍보물',
    memo: '',
    lastModifiedBy: '박병준 / 대표님',
    lastModifiedAt: DateTime(2026, 6, 30, 17, 20),
  ),
  MemberUi(
    id: 'M006',
    name: '곽로빈',
    gender: '남',
    birthDate: DateTime(2020, 10, 8),
    status: '등록',
    statusDate: DateTime(2026, 8, 1),
    motherPhone: '010-3040-1288',
    mobileAppEnabled: true,
    address: '',
    email: '',
    school: '',
    disabilityType: '자폐성장애',
    firstConsultationAt: null,
    referralSource: '지인 소개',
    memo: '',
    lastModifiedBy: '박병준 / 대표님',
    lastModifiedAt: DateTime(2026, 8, 1, 10, 10),
  ),
  MemberUi(
    id: 'M007',
    name: '곽시우',
    gender: '남',
    birthDate: DateTime(2016, 3, 6),
    status: '종결',
    statusDate: DateTime(2026, 5, 10),
    motherPhone: '010-3040-1288',
    mobileAppEnabled: false,
    address: '',
    email: '',
    school: '',
    disabilityType: '미응답',
    firstConsultationAt: null,
    referralSource: '',
    memo: '',
    lastModifiedBy: '박병준 / 대표님',
    lastModifiedAt: DateTime(2026, 5, 10, 16, 30),
  ),
  MemberUi(
    id: 'M008',
    name: '구서하',
    gender: '여',
    birthDate: DateTime(2024, 8, 13),
    status: '대기',
    statusDate: DateTime(2026, 8, 13),
    motherPhone: '010-2672-0133',
    mobileAppEnabled: false,
    address: '',
    email: '',
    school: '',
    disabilityType: '미응답',
    firstConsultationAt: null,
    referralSource: '',
    memo: '',
    lastModifiedBy: '박병준 / 대표님',
    lastModifiedAt: DateTime(2026, 8, 13, 13, 10),
  ),
  MemberUi(
    id: 'M009',
    name: '권구성',
    gender: '남',
    birthDate: DateTime(2019, 3, 31),
    status: '등록',
    statusDate: DateTime(2026, 8, 9),
    motherPhone: '010-3247-3937',
    mobileAppEnabled: true,
    address: '',
    email: '',
    school: '',
    disabilityType: '미응답',
    firstConsultationAt: null,
    referralSource: '인터넷 검색',
    memo: '',
    lastModifiedBy: '박병준 / 대표님',
    lastModifiedAt: DateTime(2026, 8, 9, 12, 5),
  ),
];
